### ISSUE TITLE
Retrieve fallback schedules

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/v2g-liberty#131]
FlexMeasures 0.17 will introduce a new way to handle fallback schedules. A separate fallback job will be triggered upon failure of the main scheduling job (whereas before the fallback schedule was computed within the same job, which is a less atomic transaction that complicated debugging).

When the FlexMeasures host upgrades to run `flexmeasures>=0.17` the API will return a status code 303 when requesting an originally failed schedule, with the *location* of the fallback schedule as a response header. This behavior requires a backwards compatible update in the `flexmeasures_client.py`, by handling the 303 status code and implementing a follow-up action to retrieve the fallback schedule . Relevant documentation will be made available, see https://github.com/FlexMeasures/flexmeasures/issues/858.

**Comment by ArdJonker** [comment]
Is work-in-progress in the addon-v2g-liberty repository.
