### ISSUE TITLE
Refactor response error handler

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/v2g-liberty#25]
We should refactor so that these functions are defined in one place, for example, as methods of a mixin class, that is subclassed by both this class and `FlexMeasuresClient`.

_Originally posted by @Flix6x in https://github.com/SeitaBV/v2g-liberty/pull/17#discussion_r963115897_

**Comment by ArdJonker** [comment]
Good suggestion.
Maybe we could also have FlexMeasuresClient handle all communication with FM. Have FlexMeasuresDataImporter and SetFMdata call a function on FlexMeasuresClient.
This would also be a nice pattern to use for WallboxClient.
What is you opinion?

**Comment by Flix6x** [comment]
That is a good thought. Then it would make sense that the response error handler is just a method of the FlexMeasuresClient. That is, we won't need a mixin.

The reponse error handler is not used by the WallboxClient - the handler deals with platform reauthorization, which is not relevant for the modbus communication to the charger - so that would be a different issue.

**Comment by ArdJonker** [comment]
Has been picked-up in the addon-v2g-liberty repository.
