### ISSUE TITLE
No need to mention NL explicitly in config variables

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/v2g-liberty#27]
`"VAT_NL"` doesn't need to mention NL explicitly.

_Originally posted by @Flix6x in https://github.com/SeitaBV/v2g-liberty/pull/17#discussion_r963111395_
      
      

        `"markup_per_kWh_NL"` doesn't need to mention NL explicitly. This is a general markup that may be used to capture consumption dependent markups, such as network tariffs and sustainability fees.

_Originally posted by @Flix6x in https://github.com/SeitaBV/v2g-liberty/pull/17#discussion_r963113119_

**Comment by ArdJonker** [comment]
Yes, i'd seen it and i'll change it as this is correct.
I was hesitant at first as i also suggested to move the calculations that those are used for from V2G-Liberty to FM.
