### ISSUE TITLE
Improve terminology of time intervals for power measurements

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/v2g-liberty#28]
The variable names are still confusing to me, and I think that is also because they are used inconsistently.

In the main docstring you mention three intervals, one of them implicitly:
- "irregular intervals", which you call "periods" (even though they aren't periodic)
- "regular intervals", which you also call "readings resolution" (and also just intervals)
- "sends results to FM hourly", which also implies a regular interval
```
App receives power changes at irregular intervals. Usually about 15 seconds apart but sometimes hours.
We want to create power usages in regular intervals of e.g. 1/12th of an hour.
Power changes: |    |    |  |    |     |               | (called periods)
Intervals:        |        |        |        |        |        |
```
I would recommend more consistent terminology and making clear definitions early on:
- Power changes occur at irregular intervals (readings): usually about 15 seconds apart but sometimes hours
- We derive a time series of power with a regular interval (that is, with a fixed period): we chose 5 minutes
- We send the time series to FlexMeasures in batches, periodically: we chose once every 1 hour

In lines 192-193 it looks to me like you are essentially redefining what a period is, because its duration is slowly growing.
```
self.period_power_x_duration += (duration * power)
self.power_period_duration += duration
```
I would describe this differently: you are tracking the energy accumulated within the regular interval of the time series of power. In other words, it shouldn't be an attribute of your "irregular period", but an attribute of your "regular interval". Maybe something like:
```
energy_since_last_power_change = duration * power
self.accumulated_energy += energy_since_last_power_change
```

In lines 209-2010 you are finalizing your weighted average calculation:
```
average_period_power = round((self.period_power_x_duration / self.power_period_duration)/1000000, 5)
self.power_readings.append(average_period_power)
```
When I'm reading this, I'm thinking: `self.period_power_x_duration` is a quantity of energy accumulated within some period (in Ws, i.e. watt-seconds, or equivalently, Joule), and you divide it over the duration of that period, in seconds (`self.power_period_duration`), which gives you the average power during that period.

But this is not the "irregular period" you defined in the docstring anymore, right? By now its duration has grown to become the duration of the "regular interval", which is `readings_resolution`.

_Originally posted by @Flix6x in https://github.com/SeitaBV/v2g-liberty/pull/18#discussion_r1021478598_

**Comment by ArdJonker** [comment]
This has been done as good as i can get it, hope you find the comments more helpful. Also removed un-needed code/comments.
