### ISSUE TITLE
Draw simple technical diagram about communication for Readme

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/v2g-liberty#5]
It should show the Wallbox Qasar, HomeAssistant and FlexMeasures and the flows between them.

The goal is for a first-time reader to get a high-level view on what is happening.

It becomes clear we also need a market integration, so that should be shown, as well. The `flexmeasures-entsoe` plugin can help with that, but different integrations are needed outside of Europe.
In the future, FlexMeasures might also require solar and consumption data, which would require another plugin (in our current case, this is the Aurum code).

**Comment by ArdJonker** [comment]
Add current architecture diagram.
![architecture](https://user-images.githubusercontent.com/6270792/216368533-aa07dfa7-6e20-47cb-8778-aa2b8ba8b6e1.png)
